export const STATES = {
  GREETING: "GREETING",
  MAIN_MENU: "MAIN_MENU",
  MEAL_PLAN_INFO: "MEAL_PLAN_INFO",
  SELECTING_SLOTS: "SELECTING_SLOTS",
  CHANGING_MEAL: "CHANGING_MEAL",
  ORDER_PLACED: "ORDER_PLACED",
};
