export const STATES = {
  GREETING: "GREETING",
  MAIN_MENU: "MAIN_MENU",
  MEAL_PLAN_INFO: "MEAL_PLAN_INFO",
  SELECTING_SLOTS: "SELECTING_SLOTS",
  CHANGING_MEAL: "CHANGING_MEAL",
  ORDER_PLACED: "ORDER_PLACED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  ACTIVE_PLAN: "ACTIVE_PLAN",
  // Subscription onboarding flow
  SELECTING_PLAN_CATEGORY: "SELECTING_PLAN_CATEGORY",
  SELECTING_DAYS: "SELECTING_DAYS",
  SELECTING_MEALS_PER_DAY: "SELECTING_MEALS_PER_DAY",
  AWAITING_LOCATION: "AWAITING_LOCATION",
  AWAITING_ADDRESS: "AWAITING_ADDRESS",
  AWAITING_PAYMENT: "AWAITING_PAYMENT",
};
